texto = input('Digite algo: ')
print (f'{texto} é do tipo pritivo? {type(texto)}')
print (f'{texto} só tem espaços? {texto.isspace()}')
print (f'{texto} é um numero?{texto.isnumeric()}')
print (f'{texto} é alfabetico?{texto.isalpha()}')
print (f'{texto} é alfanumerico?{texto.isalnum()}')
print (f'{texto} é maiusculo?{texto.isupper()}')
print (f'{texto} é minusculo?{texto.islower()}')
print (f'{texto} é alfabetico{texto.istitle()}')